watermark:
  normal:
    input_folder: "resources/input"
    handler: "process_normal_watermark"
    npy_path: "watermark_normal_200"
    opacity: 50
    quality: 30
    output_height: 1000
  foggy:
    input_folder: "resources/input"
    handler: "process_foggy_watermark"
    npy_path: "watermark_foggy_450"
    opacity: 50
    quality: 30
    output_height: 1000