view_params:
  watermark_types:
    normal:
      display: "正常"
      handler: "process_normal_watermark"
      params:
        opacity:
          label: "透明度"
          input_type: QSpinBox
          type: int
          required: false # 新增必填标记
          min: 0
          max: 100
          default: 75
        output_height:
          label: "输出高度"
          input_type: QSpinBox
          type: int
          required: false # 新增必填标记
          min: 0
          max: 2000
          default: 1000
        quality:
          label: "质量"
          input_type: QSpinBox
          type: int
          required: false # 新增必填标记
          min: 0
          max: 100
          default: 30
        enhancement:
          label: "是否增强"
          input_type: QCheckBox
          type: bool
          required: false
          options: [ true, 1, yes ]
          default: false
    foggy:
      display: "雾化"
      handler: "process_foggy_watermark"
      params:
        opacity:
          label: "透明度"
          input_type: QSpinBox
          type: int
          required: false # 新增必填标记
          min: 0
          max: 100
          default: 75
        output_height:
          label: "输出高度"
          input_type: QSpinBox
          type: int
          required: false # 新增必填标记
          min: 0
          max: 2000
          default: 1000
        quality:
          label: "质量"
          input_type: QSpinBox
          type: int
          required: false # 新增必填标记
          min: 0
          max: 100
          default: 30
        enhancement:
          label: "是否增强"
          input_type: QCheckBox
          type: bool
          required: false
          options: [ true, 1, yes ]
          default: false
model_params:
  watermark_types:
    normal:
      display: "正常"
      handler: "process_normal_watermark"
      npy_path: "watermark_normal_1000.npy"
      opacity: 50
      quality: 30
      output_height: 1000
      params:
        opacity:
          label: "透明度"
          input_type: QSpinBox
          type: int
          required: false # 新增必填标记
          min: 0
          max: 100
          default: 75
        output_height:
          label: "输出高度"
          input_type: QSpinBox
          type: int
          required: false # 新增必填标记
          min: 0
          max: 2000
          default: 1000
        quality:
          label: "质量"
          input_type: QSpinBox
          type: int
          required: false # 新增必填标记
          min: 0
          max: 100
          default: 30
        enhancement:
          label: "是否增强"
          input_type: QCheckBox
          type: bool
          required: false
          options: [ true, 1, yes ]
          default: false
    foggy:
      display: "雾化"
      handler: "process_foggy_watermark"
      npy_path: "watermark_foggy_1000.npy"
      opacity: 50
      quality: 30
      output_height: 1000
      params:
        opacity:
          label: "透明度"
          input_type: QSpinBox
          type: int
          required: false # 新增必填标记
          min: 0
          max: 100
          default: 75
        output_height:
          label: "输出高度"
          input_type: QSpinBox
          type: int
          required: false # 新增必填标记
          min: 0
          max: 2000
          default: 1000
        quality:
          label: "质量"
          input_type: QSpinBox
          type: int
          required: false # 新增必填标记
          min: 0
          max: 100
          default: 30
        enhancement:
          label: "是否增强"
          input_type: QCheckBox
          type: bool
          required: false
          options: [ true, 1, yes ]
          default: false