watermark:
  normal:
    opacity: 50
    npy_path: "watermark_normal_200"  # 不同水印类型独立配置
    output_height: 1000
    quality: 30
  foggy:
    opacity: 50
    npy_path: "watermark_foggy_200"  # 不同水印类型独立配置
    output_height: 1000
    quality: 30
watermark_types:
  normal:
    display: "正常"
    handler: "process_normal_watermark"
    npy_path: "watermark_normal_450"
    params:
      opacity:
        label: "透明度"
        input_type: QSpinBox
        type: int
        required: false # 新增必填标记
        min: 0
        max: 100
        default: 75
      allowed_formats:
        label: "允许格式"
        input_type: QComboBox
        type: list[str]
        required: false
        options: [ jpg, png ]
        default: jpg
      enhancement:
        label: "是否增强"
        input_type: QCheckBox
        type: bool
        required: false
        options: [true, 1, yes]
        default: true
  foggy:
    display: "雾化"
    handler: "process_foggy_watermark"
    params:
      default_font:
        label: "默认字体"
        type: str
        required: false
        default: "Arial"
